# Generated by Django 4.2.7 on 2026-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='apartment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='building',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='house',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='structure',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
