# Generated by Django 4.2.7 on 2026-04-10 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_contact_apartment_contact_building_contact_house_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmemailtoken',
            options={'verbose_name': 'Токен подтверждения Email', 'verbose_name_plural': 'Токены подтверждения Email'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты пользователя', 'verbose_name_plural': 'Список контактов'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Список заказов'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция в заказе', 'verbose_name_plural': 'Список позиций в заказе'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Имя параметра', 'verbose_name_plural': 'Список параметров'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'Информация о продукте', 'verbose_name_plural': 'Список информации о продуктах'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'Параметр продукта', 'verbose_name_plural': 'Список параметров продуктов'},
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='key',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='confirmemailtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_email_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='building',
            field=models.CharField(blank=True, max_length=10, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='house',
            field=models.CharField(blank=True, max_length=10, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='structure',
            field=models.CharField(blank=True, max_length=10, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('basket', 'Статус корзины'), ('new', 'Новый'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='backend.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='backend.productinfo', verbose_name='Информация о продукте'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='backend.parameter', verbose_name='Параметр'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='product_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='backend.productinfo', verbose_name='Информация о продукте'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
